export const sensationOptions = [
  { label: 'Bloating', value: 'Bloating' },
  { label: 'Pain', value: 'Pain' },
  { label: 'Stiffness', value: 'Stiffness' },
  { label: 'Fatigue', value: 'Fatigue' },
  { label: 'Swelling', value: 'Swelling' },
  { label: 'Burning', value: 'Burning' },
  { label: 'Tingling', value: 'Tingling' },
  { label: 'Numbness', value: 'Numbness' },
  { label: 'Itching', value: 'Itching' },
  { label: 'Cramping', value: 'Cramping' },
  { label: 'Throbbing', value: 'Throbbing' },
  { label: 'Weakness', value: 'Weakness' },
  { label: 'Tenderness', value: 'Tenderness' },
  { label: 'Tightness', value: 'Tightness' },
  { label: 'Aching', value: 'Aching' },
  { label: 'Soreness', value: 'Soreness' },
  { label: 'Sensitivity', value: 'Sensitivity' },
  { label: 'Heaviness', value: 'Heaviness' },
  { label: 'Spasms', value: 'Spasms' },
  { label: 'Prickling', value: 'Prickling' },
  { label: 'Pressure', value: 'Pressure' },
  { label: 'Other', value: 'Other' },
];

export const locationOptions = [
  { label: 'Whole Body', value: 'Whole Body' },
  { label: 'Head', value: 'Head' },
  { label: 'Neck', value: 'Neck' },
  { label: 'Jaw', value: 'Jaw' },
  { label: 'Chest', value: 'Chest' },
  { label: 'Upper Back', value: 'Upper Back' },
  { label: 'Lower Back', value: 'Lower Back' },
  { label: 'Abdomen', value: 'Abdomen' },
  { label: 'Shoulders', value: 'Shoulders' },
  { label: 'Elbows', value: 'Elbows' },
  { label: 'Wrists', value: 'Wrists' },
  { label: 'Hands / Fingers', value: 'Hands / Fingers' },
  { label: 'Hips', value: 'Hips' },
  { label: 'Knees', value: 'Knees' },
  { label: 'Ankles', value: 'Ankles' },
  { label: 'Feet / Toes', value: 'Feet / Toes' },
  { label: 'Eyes', value: 'Eyes' },
  { label: 'Skin', value: 'Skin' },
  { label: 'Throat', value: 'Throat' },
  { label: 'Joints (Multiple)', value: 'Joints (Multiple)' },
];
